# Generated by Django 4.1.2 on 2022-10-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('international', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('semester', models.CharField(blank=True, max_length=255, null=True)),
                ('calendaryear', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('byuid', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('class_code', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_record', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('hiredate', models.CharField(blank=True, max_length=255, null=True)),
                ('payrate', models.CharField(blank=True, max_length=100, null=True)),
                ('lastpayincrease', models.CharField(blank=True, max_length=255, null=True)),
                ('payincreaseamount', models.CharField(blank=True, max_length=100, null=True)),
                ('increaseinputdate', models.CharField(blank=True, max_length=255, null=True)),
                ('yearinprogram', models.CharField(blank=True, max_length=255, null=True)),
                ('paygradtuition', models.CharField(blank=True, max_length=255, null=True)),
                ('isterminated', models.CharField(blank=True, max_length=255, null=True)),
                ('terminateddate', models.CharField(blank=True, max_length=255, null=True)),
                ('qualtricssent', models.CharField(blank=True, max_length=255, null=True)),
                ('eform', models.CharField(blank=True, max_length=255, null=True)),
                ('eformdate', models.CharField(blank=True, max_length=255, null=True)),
                ('workauth', models.CharField(blank=True, max_length=255, null=True)),
                ('workauthdate', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
