# Generated by Django 4.1.2 on 2022-11-04 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentEmployeeInformation', '0002_professor_season_univeristyclass_semester_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={},
        ),
    ]
