# Generated by Django 4.1.2 on 2022-11-04 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentEmployeeInformation', '0004_students_name_change_alter_students_eform_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
