# Generated by Django 4.1.2 on 2022-11-04 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentEmployeeInformation', '0006_alter_student_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='byuid',
            new_name='byu_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='calendaryear',
            new_name='calendar_year',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='eformdate',
            new_name='eform_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='hiredate',
            new_name='hire_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='increaseinputdate',
            new_name='increase_input_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='international',
            new_name='international_student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='isterminated',
            new_name='is_terminated',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastpayincrease',
            new_name='last_pay_increase',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='paygradtuition',
            new_name='pay_grad_tuition',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='payincreaseamount',
            new_name='pay_increase_amount',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='payrate',
            new_name='pay_rate',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='qualtricssent',
            new_name='qualtrics_sent',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='terminateddate',
            new_name='terminated_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='workauthdate',
            new_name='workauth_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='yearinprogram',
            new_name='year_in_program',
        ),
    ]
