# Generated by Django 4.1.2 on 2022-11-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentEmployeeInformation', '0008_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('international_student', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('semester', models.CharField(blank=True, max_length=255, null=True)),
                ('calendar_year', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('byu_id', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('class_code', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_record', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('pay_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('last_pay_increase', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_increase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('increase_input_date', models.DateField(blank=True, null=True)),
                ('year_in_program', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_grad_tuition', models.IntegerField(blank=True, null=True)),
                ('name_change', models.IntegerField(blank=True, null=True)),
                ('is_terminated', models.IntegerField(blank=True, null=True)),
                ('terminated_date', models.DateField(blank=True, null=True)),
                ('qualtrics_sent', models.IntegerField(blank=True, null=True)),
                ('eform', models.IntegerField(blank=True, null=True)),
                ('eform_date', models.DateField(blank=True, null=True)),
                ('workauth', models.IntegerField(blank=True, null=True)),
                ('workauth_date', models.DateField(blank=True, null=True)),
                ('ta_assignments', models.ManyToManyField(to='StudentEmployeeInformation.classsection')),
            ],
            options={
                'db_table': 'student_employee',
            },
        ),
    ]
