# Generated by Django 4.1.2 on 2022-11-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentEmployeeInformation', '0009_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ta_assignments',
            field=models.ManyToManyField(blank=True, null=True, to='StudentEmployeeInformation.classsection'),
        ),
    ]
