# Generated by Django 4.1.2 on 2022-11-04 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentEmployeeInformation', '0010_alter_student_ta_assignments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name']},
        ),
    ]
