# Generated by Django 4.1.2 on 2022-11-04 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentEmployeeInformation', '0013_studentemployeeposition_yearinprogram_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professor',
            new_name='ISStaffMember',
        ),
        migrations.AlterModelTable(
            name='isstaffmember',
            table='is_staff',
        ),
    ]
