# Generated by Django 4.1.2 on 2022-11-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentEmployeeInformation', '0014_rename_professor_isstaffmember_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ta_assignments',
        ),
        migrations.AlterField(
            model_name='student',
            name='byu_id',
            field=models.CharField(max_length=100),
        ),
    ]
