# Generated by Django 4.1.2 on 2022-11-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentEmployeeInformation', '0015_remove_student_ta_assignments_alter_student_byu_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='byu_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
