# Generated by Django 4.1.2 on 2022-11-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentEmployeeInformation', '0016_remove_student_id_alter_student_byu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ta_assignments',
            field=models.ManyToManyField(blank=True, to='StudentEmployeeInformation.classsection'),
        ),
    ]
