# Generated by Django 4.1.2 on 2022-11-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentEmployeeInformation', '0017_student_ta_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='boolean_value',
            field=models.BooleanField(null=True),
        ),
    ]
