# Generated by Django 4.1.2 on 2022-11-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentEmployeeInformation', '0018_student_boolean_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='boolean_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='eform',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='international_student',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_terminated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name_change',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pay_grad_tuition',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='qualtrics_sent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='workauth',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
