# Generated by Django 4.1.2 on 2022-11-04 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentEmployeeInformation', '0019_alter_student_boolean_value_alter_student_eform_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ta_assignments',
            new_name='ta_history',
        ),
        migrations.CreateModel(
            name='ResearchSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='StudentEmployeeInformation.semester')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='StudentEmployeeInformation.isstaffmember')),
            ],
            options={
                'db_table': 'research_section',
                'ordering': ['semester'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='ra_history',
            field=models.ManyToManyField(blank=True, to='StudentEmployeeInformation.researchsection'),
        ),
    ]
