# Generated by Django 4.1.2 on 2022-11-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentEmployeeInformation', '0020_rename_ta_assignments_student_ta_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='byu_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='expected_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
