# Generated by Django 4.1.2 on 2022-11-04 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentEmployeeInformation', '0021_student_byu_name_student_expected_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='boolean_value',
        ),
    ]
