# Generated by Django 4.1.2 on 2022-11-07 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentEmployeeInformation', '0022_remove_student_boolean_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='StudentEmployeeInformation.univeristyclass')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='StudentEmployeeInformation.studentemployeeposition')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='StudentEmployeeInformation.semester')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='StudentEmployeeInformation.isstaffmember')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='work_assignments',
            field=models.ManyToManyField(blank=True, to='StudentEmployeeInformation.studentassignment'),
        ),
    ]
