# Generated by Django 3.2.8 on 2022-11-07 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentEmployeeInformation', '0023_studentassignment_student_work_assignments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentassignment',
            options={'ordering': ['semester']},
        ),
        migrations.AlterModelTable(
            name='studentassignment',
            table='student_assignment',
        ),
    ]
