# Generated by Django 4.1.2 on 2022-11-07 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentEmployeeInformation', '0025_remove_student_position_remove_student_ra_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchsection',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='researchsection',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='ClassSection',
        ),
        migrations.DeleteModel(
            name='ResearchSection',
        ),
    ]
